### ISSUE TITLE
Writing SENSRB takes a long time

### ISSUE THREAD

**Issue by geospatialDev** [mdaus/nitro#107]
Compared to other TREs SENSRB, especially Mod12 and Mod14 take a long time.

**Comment by asylvest** [comment]
Hey @geospatialDev  - how long is "long"?  How many bytes roughly does the SENSRB TRE take up on disk?  How about the entire NITF?   I don't suppose you can share the actual NITF with us.

**Comment by asylvest** [comment]
Youch - that's definitely significantly longer than expected.  Is it possible for you to create a source file based on `test_tre_create.cpp` that fills SENSRB out with dummy values and recreates the problem?  Then we can recreate and track down the bottleneck... we may be able to address this with better caching (i.e. maybe there are tons of small writes happening).

What OS are you on?

**Comment by geospatialDev** [comment]
I'm on linux.

**Comment by geospatialDev** [comment]
I will try to generate the data and send it across

**Comment by geospatialDev** [comment]
On debugging I see nitf_TREUtils_fillData taking the most amount of time.
