### ISSUE TITLE
Direct I/O help

### ISSUE THREAD

**Issue by tclarke** [mdaus/nitro#118]
I'm looking to perform some direct image I/O and I'm having trouble using some of the existing interfaces and modifying existing code to work for more cases.

1. I want to efficiently copy segment data to a new NITF (I.E. adding new segments and modifying limited segments but maintaining the rest). I noticed DirectBlockSource but I don't see any example usage. Any pointers on using this interface?
1. I want to directly write image data without data manipulation by NITRO. The specific case if for large data already in BIP order. I'd rather not convert to BSQ just to convert back to BIP. The interfaces seem to support this if it's only a single band but I'm having trouble modifying it to work with multiple bands. I'd like to just pass a Source and say "write this with no modification" so I can create a MemorySource pointing to my existing data.

**Comment by JonathanMeans** [comment]
Are you using the C or C++ layer? At a first look at DirectBlockSource.c, it almost look like it assumes it will be constructed from the C++ instance. 

If you're using C++, there's some example usage in `modules/c++/nitf/tests/test_direct_block_round_trip.cpp`. If you need to go through the C layer.... have a look at `modules/c++/nitf/source/BandSource.cpp`. The implementation of the C++ `DirectBlockSource` calls the C implementation, so you can see what sort of arguments it actually expects. 

Not sure on #2 yet. I'll look at it later as I have time.

**Comment by asylvest** [comment]
Also take a look at ByteProvider... it may take some code updates for your usage, but it's our lowest level way to let NITRO help you with the byte layouts / offsets but then let you handle the I/O itself as efficiently as possible for your application.

**Comment by tclarke** [comment]
I've been using the C layer (though Python...my Cython wrappers). Looks like there isn't a C equivalent? If not, I'll probably port the C++ class to C for wrapping in Cython.

**Comment by tclarke** [comment]
Nevermind, I found it in the C code

**Comment by tclarke** [comment]
I'm having a related issue now. I'm able to reproduce the test_direct_block_round_trip.cpp behavior in python but I'm having issues getting everything working when I'm modifying the data as well as copying. Specifically, I want to copy certain image segments, modify others, and add new ones. I setup the copies (for example, the first 2 segments) then add the new segments but I get an error when I create new image writer objects for the new segments.

It seems the direct copy code doesn't call nitf_Record_newImageSegment(). nitf_Writer_newImageWriter() seems ok with this when there have been no calls nitf_Record_newImageSegment() but when there have been some it blows up.

Sample call sequence: (pseudocode)
```
isources[0] = newImageSource()
isources[0].addBand(newDirectBlockSource(ireader, 0)

isources[1] = newImageSource()
isources[1].addBand(newDirectBlockSource(ireader, 1)

iseg = newImageSegment()
isources[2] = newImageSource()
foreach band:
  isources[2].addBand(newMemoryBandSource())

foreach idx in range(len(isources)):
  writer = newImageWriter(idx)   # This causes an error when idx == 2
  writer.attachSource(isources[idx])
  if idx < 2:
    writer.setDirectBlockWrite(1)
```

**Comment by JonathanMeans** [comment]
When you call `nitf_Writer_prepare()`, you end up locking the Writer to the current state of the Record. So it doesn't know how to work with things added to the Record after that. Make sure the Record is set up how you want it before calling `nitf_Writer_prepare()`.
