### ISSUE TITLE
Linking to NITRO with Visual Studio 2017

### ISSUE THREAD

**Issue by GuidedByCthulhu** [mdaus/nitro#127]
Hey Folks,

Eventually, I will be attempting to write a very simple wrapper for NITRO, so I can access it via C#.  (We are only looking to dump the geographic data, and image data; it should be fairly straightforward using the example code you've provided with the installer)

However, just to get started/familiar with NITRO, I am following your guide here (http://nitro-nitf.sourceforge.net/wikka.php?wakka=BuildingVisualStudio), trying to build an executable of the test_image_loading example.  

After following the guide, Visual Studio can see the headers and the libs. I should note that I had to include "stdafx.h" in the test code file, as VS complained.  When I attempt to build, I am presented with a number of unresolved external symbol errors.  Things such as:

`LNK2019 unresolves external symbol __imp__iob_func referenced in function getDecomplface (nitf-c.lib (Reader.c.1.0))`

Checking the.log file, I can see that I'm getting a linker warning:

`LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library`

So, assuming thats the issue, I head to the properties, Linker->Inputer-Ignore All Default Libraries, and set it to /NODEFAULTLIB

When I rebuild now, I get another pile of unresolved external symbol errors, such as:

`unresolved external symbol __stdio_common_vfprintf referencd in fucntion _vfprintf_l`

I'll admit to ignorance here, I primarily work with C#.  I have created wrappers for other C/C++ libraries in the past (GDAL for example), but the process of configuring VC++ projects is generally very opaque to me.  Assuming I can get a little assistance to get the solution up an building, I'm confident I can move onto writing the simple wrapper.

Any suggestions?

**Comment by JonathanMeans** [comment]
It looks like you found some old documentation. After you configure (e.g. `python waf configure --prefix=install --enable-debugging`), you should just be able to do `python waf msvs`, and it will build a .sln file for you.

**Comment by GuidedByCthulhu** [comment]
Is there a way to do this without using waf?  I am going to assume it will fetch missing dependencies from the Internet, which poses a problem for us (we have no external access for any of our development machines).

If there isn't, no harm, no foul; I'll just do it at home.

**Comment by JonathanMeans** [comment]
I don't know of a good way to do it without waf. However, internet access should not be a concern. All the dependencies you need come bundled with the repository.

**Comment by GuidedByCthulhu** [comment]
Alright; I'll give it a shot.

**Comment by GuidedByCthulhu** [comment]
So, I can use waf as you've mentioned above.  I open the generated solution and upgrade it from VS2015 to VS2017.  I can rebuild the "build_all_projects" to get binaries (including executables) seemingly without issue.

However, I'm actually quite lost...

Suppose we wish to work with the test_image_loading project.  I open the project properties via visual studio, navigate to the NMake subpage, and change the Output from test_image_loading.exe to renamed.exe.  If I rebuild the project; the output isn't changed...  It is still test_image_loading.exe.  I confirmed the change was made to the vcxproj (I opened it in notepad++, and  the output has been changed).  

This vcxproj is quite a bit different from what I've created in the past; it looks like most of it has been handed off the waf?  

A bit out of my depth here; how does one create a vcxproj that can produce a dll, using waf?  Typically, I would simply set the Project Defaults "Configuration Type" to "Dynamic Library", however, this vcxproj has no option for such (plus I suspect waf doesn't care whats in the vcxproj).

**Comment by JonathanMeans** [comment]
> Suppose we wish to work with the test_image_loading project. [...]

If you copy `test_image_loading.c` to `renamed.c` in the same directory, that should do what you want. `waf` will automatically find it. (May have to reconfigure.)

There is currently no good way to build DLLs. See [this discussion](https://github.com/mdaus/nitro/issues/86) for a possible workaround (and its drawbacks).

**Comment by JDanielSmith** [comment]
Given the lack of support for DLLs, your best bet is probably to create a new C++/CLI project.  This will allow you to link in the static NITRO library, it will also let you use the C++ API which is probably far easier than P/Invoking to C.

**Comment by GuidedByCthulhu** [comment]
@JonathanMeans Ah, thank you for the information on waf/the build output, AND for the possible work around.  You've been very helpful.

@JDanielSmith  The is more or less what I was intending to do in the original post.  The (outdated) wiki article about linking to NITRO didn't pan out however.  My plan was to link to NITRO in a C/C++ assembly, and export two methods I'd write myself (one to dump geo data, one to dump image data) via dllexport.  I've done that in the past for other libraries (GDAL); though I do fully admit I am not very knowledgeable about setting up VC++ projects.

Though you're not wrong about just having a CLI app - I might be quickest to do just that.  I could use one of the auto generated vcxproj files as an example, and create a new executable(s) which do the actions I need.  I could simply spin this executable up using Process.start().  It's inelegant, but it would work fine.

**Comment by JDanielSmith** [comment]
C++/CLI is a Microsoft programming language for connecting managed and unmanaged code, it has nothing to do with a "Command Line Interface" (CLI in this case means Common Language Infrastructure, i.e., .NET).

[Wikipedia](https://en.wikipedia.org/wiki/C%2B%2B/CLI)
[.NET Programming with C++/CLI (Visual C++)](https://docs.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp?view=vs-2019)

**Comment by Miakonn** [comment]
@GuidedByCthulhu I would like very much to get a copy of your working VS2017 solution, including  changes you made to the code. When I ran "python waf msvs", and opened it VS2017 I didn't get a single working project. (I used Windows 10 with cygwin.)

I need to build a program or library to convert jpg/png file to NSIF 1.0 file (and add approriate the metadata).

**Comment by GuidedByCthulhu** [comment]
@Miakonn I'm afraid I was never able to get a wrapper for NITRO working.  I cut my losses and simply made a wrapper for the GDAL.  The GDAL can extract the raster data (and dumps the geographic data as an XML file); not sure if it can do the reverse (with jpg/png file), but you can try?

**Comment by Miakonn** [comment]
I also went for the GDAL... but thanks for answering.

**Comment by JDanielSmith** [comment]
We can look at this again with VS2019 if still needed.
