### ISSUE TITLE
Typo in MSTGTA plugin

### ISSUE THREAD

**Issue by ca-mtg** [mdaus/nitro#128]
TGTEVEL and TGTEVELUNIT

EVEL should be ELEV (for elevation) according to NITF standard.

https://github.com/mdaus/nitro/blob/be04d0db8a5aa4459a6a37c926c46315ee48c833/modules/c/nitf/shared/MSTGTA.c#L38-L39

**Comment by JonathanMeans** [comment]
@ca-mtg Thanks for bringing it up. Fix has just been merged into master.
