### ISSUE TITLE
Linking to Nitro c++ with QtCreator

### ISSUE THREAD

**Issue by Kyeiv** [mdaus/nitro#139]
Hi, i am trying to build a simple app with nitro using QtCreator. I made the following steps:

> python waf configure --enable-debugging --prefix=installed
> python waf build
> python waf install

Now i don't know how to link it to my IDE and cannot find the answer, can you guys help?
using Ubuntu 18.04

@edit i also didn't find any info if the nitro library allows to display a nitf image

**Comment by JonathanMeans** [comment]
There's no built-in support for displaying images, but you could, for example, using the Python bindings to get the raw image data, then use `PIL` or `matplotlib` or similar from there. See `modules/python/nitf/samples/test_image.py` for an example of converting NITF to JPEG. 

Never used Qt Creator, so I don't think I can say anything super specific. Basically you'll want to be sure `install/include` is on the include path and `install/lib/` is on the library path. You'll at least need to link to `libnrt-c` and `libnitf-c` to get the C library. If you want to use C++ you'll have to pull in basically everything in there.
