### ISSUE TITLE
C++ round trip issues

### ISSUE THREAD

**Issue by Kyeiv** [mdaus/nitro#140]
Hi, I built and run the test_round_trip.cpp and test_direct_block_round_trip.cpp unfortunately i encountered some issues:

test_direct_block_round_trip.cpp - after running crashes with SIGSEGV, Segmentation fault.
GDB output:
Program received signal SIGSEGV, Segmentation fault.
__memmove_sse2_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:403
403	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_sse2_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:403
#1  0x000055555556642d in TestDirectBlockSource::nextBlock (
    this=0x555555879990, buf=0x55555587dc70, block=0x7ffff7f1a010, 
    blockNumber=0, blockSize=393216) at ../Nitro_usage2/main.cpp:39
#2  0x000055555556feeb in nitf::DirectBlockSource::nextBlock (
    callback=0x555555879990, buf=0x55555587dc70, block=0x7ffff7f1a010, 
    blockNumber=0, blockSize=393216, error=0x7fffffff4ba0)
    at ../modules/c++/nitf/source/BandSource.cpp:150
#3  0x00005555555a3db6 in DirectBlockSource_read (data=0x55555587bdc0, 
    buf=0x55555587dc70, size=1024, error=0x7fffffff4ba0)
    at ../modules/c/nitf/source/DirectBlockSource.c:80
#4  0x00005555555b9f50 in ImageWriter_write (data=0x555555874f30, 
    output=0x555555838530, error=0x7fffffff4ba0)
    at ../modules/c/nitf/source/ImageWriter.c:169
#5  0x00005555555cc7e7 in writeImage (imageWriter=0x555555839050, 
    output=0x555555838530, error=0x7fffffff4ba0)
    at ../modules/c/nitf/source/Writer.c:1493
#6  0x00005555555ccef6 in nitf_Writer_write (writer=0x555555871db0, 
    error=0x7fffffff4ba0) at ../modules/c/nitf/source/Writer.c:1724
#7  0x0000555555582699 in nitf::Writer::write (this=0x7fffffff4b90)
    at ../modules/c++/nitf/source/Writer.cpp:80
#8  0x0000555555563cf7 in main (argc=1, argv=0x7fffffffdd58)
---Type <return> to continue, or q <return> to quit---
   main.cpp:124

 test_round_trip.cpp - should copy input file but it creates a different one

My input data i_3228c.ntf
from [https://gwg.nga.mil/ntb/baseline/software/testfile/Nitfv2_1/scen_2_1.html](url)

To preview images i used my custom Qt + Gdal viewer:
`
#include <QApplication>
#include <QDebug>
#include <gdal/gdal.h>
#include <gdal/gdal_priv.h>
#include <stdlib.h>
#include <iostream>
#include <string>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <QLabel>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    qDebug() << "start";

    GDALAllRegister();

    const char* input = argv[1];
    const char* output = argv[2];

    GDALDataset * pOldDS;
    pOldDS = (GDALDataset*) GDALOpen(input, GA_ReadOnly);

    // Get raster image size
    int rows = pOldDS->GetRasterBand(1)->GetYSize();
    int cols = pOldDS->GetRasterBand(1)->GetXSize();
    int channels = pOldDS->GetRasterCount();

    // Create each separate image as grayscale
    std::vector<cv::Mat> image_list(channels, cv::Mat( rows, cols, CV_8UC1 ));
    cv::Mat output_image;

    // Iterate over each channel
    for (int i = 1; i <= channels; ++i)
     {
        // Fetch the band
        GDALRasterBand* band = pOldDS->GetRasterBand(i);
        // Read the data
        band->RasterIO( GF_Read, 0, 0,
                        cols, rows,
                        image_list[i-1].data,
                        cols, rows,
                        GDT_Byte, 0, 0);
     }

    GDALClose(pOldDS);

     // Merge images
     cv::merge( image_list, output_image );

     // Create the QImage
     QImage qt_image( output_image.data,
                      cols,
                      rows,
                      QImage::Format_RGBA8888);

    // Do some stuff with the image
    QLabel myLabel;
    myLabel.setPixmap(QPixmap::fromImage(qt_image));

    myLabel.show();

    qDebug() << "finish";

    return a.exec();
}
`

**Comment by JonathanMeans** [comment]
Argh, yeah this library has not been tested thoroughly against multi-band imagery. In particular, blocked multi-band imagery is a known issue that I just haven't had the time to fix.

I'll see what I can do about getting this to be higher priority. In the mean time... I'm afraid you're going to be stuck with single-band imagery.

**Comment by Kyeiv** [comment]
oh alright, can i ask you to maybe provide me some sample data that work on the current version of library then?

**Comment by JonathanMeans** [comment]
https://six-library.s3.amazonaws.com/sicd_example_RMA_RGZERO_RE16I_IM16I.nitf
https://six-library.s3.amazonaws.com/sicd_example_RMA_RGZERO_RE32F_IM32F.nitf

**Comment by Kyeiv** [comment]
thanks!

**Comment by Kyeiv** [comment]
one more question, is the whole library dealing with the multi-band imagery issue?

**Comment by JonathanMeans** [comment]
That's a safe assumption.
