### ISSUE TITLE
Using Plugins in NITRO 2.8 32-Bit

### ISSUE THREAD

**Issue by mbarthmuc** [mdaus/nitro#153]
Hello,

I am using the NITRO Library Version 2.8 in my C++ project in order to read and write the data of NITF Files. I can only use a 32-bit version in this project. As the static libraries which are installed with the "...setup.exe" for version 2.8 seem to be 64-bit in both versions (32-bit and 64-bit), I have compiled the code and made new libraries, which works fine so far. I can read and write the data of NITF files, mostly by using the code samples in "test_image_loading++.cpp". The only thing which does not work is using the plugins, which I need in order to compress or decompress the images in the NITF Files (so I can only read uncompressed images so far).

When the image reader is set for a compressed image (in the following line in the writeImage-Function)

nitf::ImageReader deserializer = reader.newImageReader(imageNumber);

there is an exception which says "Decompression handlers not set". This seems to be because the plugin "LibjpegDecompress.dll" which is neccessary for decompression could not be loaded.
My NITF_PLUGIN_PATH is set to the correct path, so the dll file can be found, the problem is that the dll can not be loaded. When i try to load it explicitly with 
LoadLibrary("C:\\Program Files (x86)\\nitro-nitf\\nitro-2.8\\share\\nitf\\plugins\\LibjpegDecompress.dll");
then i just get a NULL pointer, so it seems this plugin does not fit together with my 32-bit version of the nitf libraries.
Does anyone have the same problems? Is there a 32-bit version of the plugin dlls in version 2.8?
I have also tried to use the 32-bit plugings from older NITRO versions, these can be loaded, but then the reader throws an exception in the "read" command, maybe because the NITRO versions are not the same...

thank you for your help,

Michael

**Comment by JonathanMeans** [comment]
A couple debugging questions:

Can you try `LoadLibrary` again with the backslashes escaped? e.g. `LoadLibrary("C:\\Program Files (x86)\\nitro-nitf\\nitro-2.8\\share\\nitf\\plugins\\LibjpegDecompress.dll");`

NITRO loads the decompression plugins through PluginRegistry.c: `nitf_PluginRegistry_loadPlugin()` -> `insertPlugin()` Can you check if any of the plugins are getting loaded through there?

**Comment by mbarthmuc** [comment]
thank you for looking at my problem...

I had the backslashes escaped already before, seems like they were set to single backslash when copying here.

Now I tried:

bool loaded = nitf_PluginRegistry_loadPlugin("C:\\Program Files (x86)\\nitro-nitf\\nitro-2.8\\share\\nitf\\plugins\\LibjpegDecompress.dll", &error);

which returns false, I also tried some other dlls of the "plugins" path, always the result is false, seems none of them will load correctly.

**Comment by mbarthmuc** [comment]
What is "insertPlugin()" you mentioned.... a function i have to call??

**Comment by JonathanMeans** [comment]
`insertPlugin()` is what `nitf_PluginRegistry_loadPlugin` calls to register a plugin once it's loaded, but it looks like we're not even getting that far.

What do you get for `GetLastError()` after `LoadLibrary()` fails?

**Comment by mbarthmuc** [comment]
GetLastError() returns 193

**Comment by JonathanMeans** [comment]
Can you share the contents of `target/config.log`?

**Comment by mbarthmuc** [comment]
The dll i am building is called NitroWrapper, so my log File is "NitroWrapper.log" which i add here (Debug Version)
[NitroWrapper.log](https://github.com/mdaus/nitro/files/3777793/NitroWrapper.log)

**Comment by JonathanMeans** [comment]
So are you not building with waf, then? I was after the log from the configuration step.

**Comment by mbarthmuc** [comment]
No, i am building in Visual Studio 2017

**Comment by mbarthmuc** [comment]
Hello,
as I still don't have a solution for the problem above (I can't load the plugin for compression to my NITRO application), and there are also problems using uncompressed images, I have some basic questions:

My implementation uses the NITRO library to read in the jpg file, write the 3 color bands for RGB to a raw image record, set all necessary parameters in the NITF header and image sub-header, and finally write the raw image record to the NITF image data section. I don’t use any compression for the NITF image data (set the parameter “Image Compression” to “NC”).
The result I get can be viewed with the online NITF viewer (https://hawkstream.net/nitf.html) which shows my original image, but unfortunately not in XnView (which is supposed to be able to show NITF files).

I had the opinion, that you always have to convert the image to the NITF format (compressed or uncompressed), but maybe I am wrong and it is also allowed to put the pure jpg or bmp data into the image data section of the NITF file??
What does "compression" in the NITF file mean? Is putting the jpf file (as it is) to the data section also a kind of compression (as there is the value "C3" for jpg compression) or is the NITF compression something different but "C3" means it uses the same algorithm as in jpg format but still does its own compression?

Can anyone enlighten me?

Thanks for your help

**Comment by JonathanMeans** [comment]
Since you mention .jpf extension, are you working with JPEG or JPEP 2000 (J2K)?

In the case of J2K, you want IC=C8, and the *codestream* is embedded directly as the image data. [This website](https://gwg.nga.mil/ntb/baseline/software/testfile/Jpeg2000/jpeg2k.htm) has examples of how it fits together.

For JPEG, I'm not sure, but I assume it would be similar.

**Comment by mbarthmuc** [comment]
Hello Jonathan, thank you for your answer.
I tried to use JPEG format (IC=C3)
According to the NITF examples on the website you mentioned, I assume putting a JPG file as it is into the NITF image data section and "No Compression" is NOT the same. Obviously, no compression means putting the raw image data for each RGB band into the data section.
My problem is, it does not work with my system for neither of the 2 cases.
When I use IC=NC (no compression), I can put the raw image data (which I have read from a JPG file with the function jpeg_read_scanlines() from the NITRO jpeglib) into the NITF record (using an nitf::Writer with a nitf::ImageSource). The result is an uncompressed NITF file which I can read in and convert back to a jpg file with the NITRO library functions in my own system.
But as the XnView tool cannot open this file (it can open the uncompressed NITF sample files from the website), I assume something is wrong with this file.
When I try to generate a JPG compressed NITF file (IC=C3) or try to read in a JPG compressed NITF file, I have the problem that I get a NITF exception saying "compression/decompression handler not set" as soon as I try to use the imageReader or imageWriter. This is probably the result of not being able to load the "LibjpegDecompress.dll" library which I mentioned above.
So I cannot generate a correct uncompressed NITF file and I cannot read or write a NITF with jpg compression.
Do you have an idea how I could put the (already JPG compressed) JPG data right into the NITF image data section without the LibjpegDecompress.dll which I can obviously not use?

**Comment by bradh** [comment]
Note that JPEG NITF isn't quite the same as "JPEG in JFIF". Please see the MIL-STD for the additional tables you need to include.

**Comment by mbarthmuc** [comment]
Hello bradh,
what do you want to say with that? Does "JPEG NITF isn't quite the same as "JPEG in JFIF" mean that it is not possible to just set the JPG data as it is into the the NITF image data section, but it always has to be converted with a jpg compression function from the LibjpegDecompress.dll (or another function of the NITRO library) before putting into the NITF?
I have read the MIL-STD-6017B and I set all parameters in the NITF header and the NITF subheader which are mentioned as "mandatory" there. What do mean with "additional tables"??

**Comment by JonathanMeans** [comment]
Unfortunately, NITRO does not currently support JPEG compression. Decompressing JPEGs is supported through LibjpegeDecompress plugin.

I'm not terribly familiar with the standards for C3, so I don't want to speculate more than I already have. [This document](https://gwg.nga.mil/ntb/baseline/docs/stdi0003/nitficuh0998.pdf) will probably be useful. See also [this blog post](http://jeffmatherphotography.com/dispatches/2010/05/nitf-jpeg/) describing the compression in more human language.

The "right" way to do it would be to write a JPEG compression plugin. If you have already-compressed data in the correct format, you could try setting up the image subheader as if the compressed data were a normal image, and then use a binary editor to adjust the values afterwards. I don't recommend this, but it could work. 

I'll push up the request for supporting JPEG compression.

I don't understand your other problem. You're manually creating a NITF from image data you got by manually decompressing a JPEG, and NITRO can read it but not XnView?

**Comment by mbarthmuc** [comment]
Thanks again. I think I understand what you mean:
Decompressing JPEGs would be possible in theory, but is no option for me at the moment, because I am not able to load the LibjpegDecompress plugin.
Compression of JPEGs (without writing my own compression plugin) could be done by taking the already-compressed data, using the ImageWriter of the NITRO library by setting the compression type to "No Compression" and afterwards manipulate the NITF file to adjust the the compression type to "C3". But there are two problems I think: First, as "bradh" stated, the JPEG NITF isn't quite the same as JPEG, so I cannot take usual JPG data for that, and second, how could I find the position of the "Compressin Type" in the binary data?

For the second problem: I take usual JPEG data, read it with a function of the NITRO library, and I put the 3 color bands of the raw image data to the NITF image data section using the nitf::Writer class (IC is set to No Compression). The result is a NITF file which I can convert back to JPEG using the corresponding functions of NITRO library, but XnView says it cannot open this file, although it can open other uncompressed NITF files from the sample website. So something is different between my uncompressed NITF file and the samples...

**Comment by JonathanMeans** [comment]
So the underlying problem you're trying to solve is you have a JPEG, and you want to create a NITF with the same image as the JPEG?

The compressed NITF option is probably not the way to go here. For the other approach, if you can give me the NITF or the header (you can run install/bin/show_nitf on it to dump the header), I can try to see if anything stands out as invalid. You could also try opening it with some other open source NTIF reader (e.g. SarPy, MATLAB SAR Toolbox), and see if that works/where in the code it's choking.

**Comment by mbarthmuc** [comment]
"So the underlying problem you're trying to solve is you have a JPEG, and you want to create a NITF with the same image as the JPEG?"  yes, that's exactly what I want to do.

Here is the NITF file that my application has produced from a JPEG. Maybe the problem is that IC is set to "No Compression" (which I have to do in order to be abel to use the nitf::Writer) but the data is in fact JPG compressed?
[myImage.zip](https://github.com/mdaus/nitro/files/4510197/myImage.zip)

**Comment by bradh** [comment]
MIL-STD-188-198A provides the requirements for JPEG encoding (C3/M3). You need the huffman tables. See https://gwg.nga.mil/ntb/baseline/docs/188_198a/jpeg.pdf

**Comment by mbarthmuc** [comment]
Thanks for your answers. I still haven't quite got it.
In MIL-STD-188-198A, there is a description of the JPEG compression and decompression algorithm within the NITF standard.
As you stated, "JPEG NITF isn't quite the same as "JPEG in JFIF".
In my understanding, the JPEG File Interchange Format (JFIF) describes how to save JPEG coded data, but it only uses a subset of the possibilities of JPEG, for example it only allows the YCBCR color space, whereas JPEG also allows the RGB color space. But in MIL-STD-188-198A both color spaces are possible as options in the JPEG compression within NITF. So it looks to me as if I can use all possibilties of JPEG compression in NITF, not only the subset which is used in JFIF. Which would mean that the data of every JFIF file could be used as image data in a NITF file.
Is that correct so far or am I wrong?
If it is correct, then I don't undestand why there are different compression/decompression algorithms in the NITRO library for reading/writing a JPEG file and reading/writing JPEG format to a NITF file. For reading and writing the JPEG data from a file I can use the jpeg_start_decompress() and jpeg_start_compress() functions from the jpeglib (which is part of NITRO), this seems to work fine.  But for writing the JPEG data into the NITF structure you stated "NITRO does not currently support JPEG compression"...
Can you describe the difference to me, or what I misunderstood?

**Comment by bradh** [comment]
I think you can do whatever you want. Just be cautious that not everything is valid NITF.

**Comment by mbarthmuc** [comment]
Of course I want to produce a VALID NITF. I want to exchange NITF files with other systems, so I need to stick to the NITF standard.
The questions remains if the data of a JFIF file could be used in the image data section of a NITF, and if so, why are there different compression/decompression algorithms in the NITRO library for reading/writing a JPEG file and reading/writing JPEG format to a NITF file??

**Comment by bradh** [comment]
If you want to produce valid NITF with C3/M3 encoding, you need to have data that matches MIL-STD-188-198A (including the embedded quantization tables, which you need to flag in COMRAT; and pixel ordering). Its possible a JFIF file might give you that, but I think its unlikely.

FWIW, there isn't much focus on JPEG any more; since most people have migrated to JPEG2000.

**Comment by mbarthmuc** [comment]
Sorry again for bothering, but I still dont get any further. 
What I want to do: Take an image and put that image into a valid NITF in order to send it to other partners which use the NITF standard, and read an image from a NITF file which I receive from other partners. I don't care about the compression type (or even uncompressed data) as long as I can produce and read valid NITF with an image inside, and I don't want to implement a compression plugin on my own.
My hope was that the NITRO library could exactly do that for me (put an image into a NITF and read an image from a NITF), but as I understood Brad and Jonathan, there is currently no way to make NITRO do that, as long as I don't write my own compression.
So does anyone have a hint if there is another open library which I can use to solve my problem?
Thanks again.

**Comment by bradh** [comment]
I think that is a misrepresentation of what I wrote. I said you can't just drop the content of a random JPEG file into an image segment and be sure that it is valid.

If all you want it is to make a file, maybe https://github.com/mdaus/nitro/blob/master/modules/python/nitf/samples/test_make_nitf.py would help.

Other options depend on your functional needs, which you haven't really described, but GDAL/OGR is popular. I have one in Java, but I don't think it is appropriate to advertise in someone else's project.

**Comment by mbarthmuc** [comment]
"...your functional needs, which you haven't really described"
Hmm... what else can I describe? As I have written above, I have an application written in C++ which I want to use to take any image from my file system (i.e. a jpeg) and put that image into a valid NITF which can be sent to any other partner (who uses the NITF standard) by my application, no matter which compression type as long as it is a valid NITF. And also read images from NITF files which I get from other partners. What other "functional needs" should I describe?
When you say that I "can't just drop the content of a random JPEG file into an image segment and be sure that it is valid" this means to me, that I cannot just take any JPEG file and put it into a NITF file as it is, but I would have to write my own compression library (which I had the hope NITRO would do for me). So I can NOT use NITRO to do what I want (take any jpeg image and put it into a NITRO file) as long as I don't have my own compression library. So what is the misinterpretation?
The example you postet seems to be a python script, what I am looking for is a C++ code example or library to do what I have described...

**Comment by bradh** [comment]
I'm sorry I appear to offended you, but I think we're talking at cross purposes. I'm only guessing at licensing, performance, image size, colour depths and formats, TRE support, and a host of other format needs, which makes this hard to provide a definitive answer.

However I think if you can work out how to open your source file, decompress it, and put it into the NITRO API, then I think NITRO could do what you want. It might not be able to do C3/M3 encoding, but that no longer appears to be a requirement if uncompressed or JPEG 2000 is OK.

I thought that Python would be a good way to see the concept. The python binding is fairly directly mapped to the underlying C implementation. Sorry that didn't work for you.
Is https://github.com/mdaus/nitro/blob/master/modules/c%2B%2B/nitf/tests/test_create_nitf%2B%2B.cpp better?

**Comment by mbarthmuc** [comment]
Hello Brad,
you did not offend me, everything is ok. The thing is, I think I just don't get closer to a solution of my problem. 
"However I think if you can work out how to open your source file, decompress it, and put it into the NITRO API, then I think NITRO could do what you want." - That is exactly what I try to do since several weeks, my application opens a jpeg file with libjpeg successfully, populates the NITF header, adds the image segments with the color bands and writes everything into NITF with the NITRO library (with no compression), but the result appears to be not a valid NITF and I canb not figure out what the problem is.

**Comment by bradh** [comment]
I don't think I can help much with 'not a valid NITF'. I'd suggest starting a new ticket, showing a small sample, and describing what you did, what you expected to happen, and what happened instead.
