### ISSUE TITLE
Write CGM Data to NITF File

### ISSUE THREAD

**Issue by mbarthmuc** [mdaus/nitro#154]
Hello,

as stated in the issue below, I am using the NITRO Library Version 2.8 in my C++ project in order to read and write the data of NITF Files (32-bit version).
Now I try to read and write graphic segments from and to NITF Files which contain CGM data. Reading the CGM data from a NITF File works fine, I am using the function cgm_MetafileReader_read() from MetafileReader.h to get the data, then I can process the CGM data from the metafile.
The other way does not work yet. I want to create a NITF File with a graphics segment containing CGM data. I tried to use the cgm_MetafileWriter_write() funtion in order to write the CGM data (which is produced in my createCGM() function) to a buffer with the help of an nitf_IOInterface and then write the content of the buffer to the NITF File, but this does not work. The MetafileWriter does not write anything to the nitf_IOInterface. See the code below... Maybe I have to initialize the nitf_IOInterface first? But I don't have a data source in this case for the Interface!?
Can anyone help?

void NitroWrapper::CreateNitfFromCgm(k2::CgmData, const std::string &nitf_path)
{
	nitf::Record record;
	nitf_Error error;
	nitf::ListIterator iter;
	nitf::ListIterator end;
	char *buffer = NULL;
	nitf::Writer writer;
	
	cgm_Metafile *metafile = NULL;
	cgm_MetafileWriter *cgm_writer = NULL;
	nitf_IOInterface *input = NULL;

	/* open the output IO Handle for the NITF File */
	nitf::IOHandle output(nitf_path, NITF_ACCESS_WRITEONLY, NITF_CREATE);

	populateFileHeader(record, nitf_path);

	/* add a graphic segment */
	addGraphicSegment(record);

	writer.prepare(output, record);

	iter = record.getGraphics().begin();
	end = record.getGraphics().end();

	for (int count = 0; iter != end; ++iter, ++count)
	{
		nitf_IOHandle io_handle = nitf_IOHandle();
		input = nitf_IOHandleAdapter_construct(io_handle, NITF_ACCESS_READONLY, &error);

		cgm_writer = cgm_MetafileWriter_construct(&error);
		assert(cgm_writer);

		metafile = createCGM(count, &error);

		// Write CGM Metafile to IO Handle
		cgm_MetafileWriter_write(cgm_writer, metafile, input, &error);

		int size = nrt_IOInterface_getSize(input, &error);

		buffer = new char[size];

		// Read Data from IO Handle and write to Buffer
		nitf_IOHandle_read(input, buffer, size, &error);
		
		nitf::SegmentMemorySource readerSource(buffer, size, 0, 0, true);
		mem::SharedPtr<::nitf::WriteHandler> segmentWriter(new nitf::SegmentWriter(readerSource));
		
		writer.setGraphicWriteHandler(count, segmentWriter);
	}

	writer.write();
}

**Comment by mbarthmuc** [comment]
Thanks for your answer. I have tried NITF_ACCESS_READWRITE when constructing the nitf_IOInterface, but the result is the same, the function cgm_MetafileWriter_write() does not write anything to the handle (size is -1). It seems like you cannot use the nitf_IOInterface without having defined a data source (even though I want to use the metafile data as a source and only want to write to the nitf_IOInterface).

But it works if I construct the nitf_IOInterface with a file handle as data source:

const char *filename = "C:\\Temp\\test.cgm";
input = nrt_IOHandleAdapter_open(filename, NITF_ACCESS_READWRITE, NITF_CREATE, &error);

Then I can write to nitf_IOInterface with cgm_MetafileWriter_write() and I can read the data to a buffer with nitf_IOHandle_read(input, buffer, size, &error);

This is a workaround, because I don't really need a file to store my data, but at least it seems to work.
But now I have another problem: After writing the CGM data which I have in my buffer (the buffer size is reasonable) to the NITF file (using the nitf::Writer class) i get a nitf file, but when reading in this file again, the function cgm_MetafileReader_read() crashes (which it does not when reading in some other sample NITF files, in this case i can access the CGM data with this function) so it seems the NITF file which i produce does not contain a correct formatted graphics segment with CGM data.
I have no idea what is going wrong...

**Comment by JonathanMeans** [comment]
The CGM module is not something that gets a lot of use, so it may just need an update. If you can provide me a link to the NITF you're using for this example, I would be better able to look into this, as time allows.

**Comment by mbarthmuc** [comment]
I used the "U_1060a" file from https://gwg.nga.mil/ntb/baseline/software/testfile/Nitfv2_0/scen_2_0.html because i wanted to ckeck for CGM polylines.

**Comment by mbarthmuc** [comment]
Just for information: Meanwhile I solved the problem. If you use nrt_IOInterface_read() instead of nitf_IOHandle_read() in order to read the Metafile from the interface to the buffer and rewind the filestream before with nrt_IOInterface_seek() then it works. See code below.

void NitroWrapper::CreateNitfFromMetafile(cgm_Metafile *metafile, const std::string &nitf_path)
{
	nitf::Record record;
	nitf_Error error;
	nitf::ListIterator iter;
	nitf::ListIterator end;
	char *buffer = NULL;
	nitf::Writer writer;
	cgm_MetafileWriter *cgm_writer = NULL;
	nitf_IOInterface *input = NULL;

	/* open the output IO Handle for the NITF File */
	nitf::IOHandle output(nitf_path, NITF_ACCESS_WRITEONLY, NITF_CREATE);

	populateFileHeader(record, nitf_path);

	/* add a graphic segment */
	addGraphicSegment(record);

	writer.prepare(output, record);

	iter = record.getGraphics().begin();
	end = record.getGraphics().end();

	for (int count = 0; iter != end; ++iter, ++count)
	{
		const char *filename = "C:\\Temp\\test.cgm";
		input = nrt_IOHandleAdapter_open(filename, NITF_ACCESS_READWRITE, NITF_CREATE, &error);

		cgm_writer = cgm_MetafileWriter_construct(&error);
		assert(cgm_writer);

		// Write CGM Metafile to IO Handle
		cgm_MetafileWriter_write(cgm_writer, metafile, input, &error);

		int size = nrt_IOInterface_getSize(input, &error);

		buffer = new char[size];

		// ftm: rewind filestream
		int result = nrt_IOInterface_seek(input, 0, NRT_SEEK_SET, &error);

		// Read Data from IO Interface and write to Buffer
		// nitf_IOHandle_read(input, buffer, size, &error);

		// ftm: use nrt_IOInterface methods
		nrt_IOInterface_read(input, buffer, size, &error);

		nitf::SegmentMemorySource readerSource(buffer, size, 0, 0, true);
		mem::SharedPtr<::nitf::WriteHandler> segmentWriter(new nitf::SegmentWriter(readerSource));

		writer.setGraphicWriteHandler(count, segmentWriter);
	}

	writer.write();

	output.close();
	nrt_IOInterface_close(input, &error);
}
