### ISSUE TITLE
Incorrect Illum Azimuth Angle field in RSMIDA TRE

### ISSUE THREAD

**Issue by ctophermorgan** [mdaus/nitro#170]
The RSMIDA TRE field IE0 is used for both Range and Azimuth Angle in the RSMIDA TRE leading to a duplication of the Range value in both fields.

The Illum Azimuth Angle should be IA0

**Comment by ctophermorgan** [comment]
Will this go into a new 2.8 build and released?

**Comment by JonathanMeans** [comment]
If you need a new release, I could do 2.9 in the near future.

**Comment by ctophermorgan** [comment]
I was going to pull in the latest release in the next couple of weeks since I am back at 2.7. I would like to have this RSMIDA fix as well. However, if there is not enough changes to merit a release I can easily overlay this minor fix. I have this fix locally in my 2.7 version already.

Were you planning a 2.9 release in the future before this issue?

**Comment by JonathanMeans** [comment]
The release schedule is more-or-less "on request" as users who need to work from releases want to use updates. That said, now's a good time for it anyway, given the latest updates. 

FYI, if you're changing 2.7 locally, you may need this change too: https://github.com/mdaus/nitro/pull/129/files

**Comment by ctophermorgan** [comment]
I would happily take a new release. Do you have a timeframe of when 2.9 will be released so that I know when I can pull it?

**Comment by JonathanMeans** [comment]
There's one more bugfix I'd like to get in, so I'd say about a week.
