### ISSUE TITLE
Issues using waf on RHEL 7 including missing references (check.h, sys/time.h, sqrt, pthread)

### ISSUE THREAD

**Issue by ctophermorgan** [mdaus/nitro#173]
NITRO 2.7 (we are currently in the process of getting 2.8 (but approval process is not fast)
RHEL: 7.7, Kernal: (uname-r): 3.10.0-1062.12.1.el7.x86_64

The following command fails: python waf configure --enable-debugging --disable-matlab --with-defs="-DNITF_DEBUG"  --prefix=../install

I noticed platform=x86_64-unknown-linux-gnu". Should unknown be rhel or redhat? Am I missing an argument?

The command outputs the following as items that were not found: check.h, -lsqrt, -lpthread, sys/time.h related items: BSDgettimeofday, gethrtime, hrtime_t

I noticed the missing sys/time.h related items could be Solaris based. Am I missing an argument to indicate Linux Redhat?

When I remove --with-defs from the configure line then -lpthread is found and the configure succeeds. Is there an issue with using --with-defs? Also, I still get not found messages for the other items above. How do I clean up these items? 

This gets me to the point where I can also build successfully and use the libraries. However, I noticed that the j2k shared libraries are missing (J2KCompress|Decompress.so). Is there a specific config parameter to allow the build of thes libraries?

What was the command that was used to build the 2.7 delivered nitro-nitf-2.7-x86_64-linux-gnu-64-41157.zip contents? What was the evironment it was built on (RHEL/GNU/C++/C/Matlab versions, etc.)?

**Comment by JonathanMeans** [comment]
I am building on RHEL 6.10, gcc 4.9.1, python 2.7 For release 2.7, both of these commands work fine for me, including LibjpegDecompress:

    waf configure --prefix=install --enable-debugging install

    waf configure --prefix=install install

    waf configure --prefix=install --disable-matlab install


> Is there an issue with using --with-defs? 

Probably. The `NITF_DEBUG` flag is probably not going to do much for you. If you're sure you want it, you can add `conf.define('NITF_DEBUG', 1)` to the `configure` function in the top-level wscript.

The j2k shared libraries should be getting installed into `<install>/share/nitf/plugins` by default. If they're not there, can you attach your `target/config.log`?

**Comment by ctophermorgan** [comment]
I attempted adding config.define('NITF_DEBUG',1) to c/wscript and there were error building test_debug_mem_1, test_image_loading, and test_replace_field.  I also attempted builking RHEL 6 and had the same issues. I can live without the DEBUG outputs.

Unfortunately, I cannot easily provide the config.log file. Sorry about this, I know this could be helpful.

I get the LibjpegDecompress.so but not the J2KCompress.so and J2KDecompress.so. 

Any other thoughts on the "not found" items above?

So at this point I am not blocked and moving forward. I was just trying to cleanup and replicate as close to the delivered nitro-nitf-2.7-x86_64-linux-gnu-64-41157.zip with my TRE updates as I can.

**Comment by JonathanMeans** [comment]
The symbols you're not finding are fine. It's from a more global configuration that seems to be checking for everything it can think of, so it's available for the build system to ask about in case it wants to in whatever project. If it was required, the configuration would fail.

For the 2.7 release, it looks like you have to pass `--with-j2k=openjpeg` at configure time in order to build the j2k module.
