### ISSUE TITLE
What is the best way to populate an external data structure from Nitro

### ISSUE THREAD

**Issue by alanlav** [mdaus/nitro#193]
I would like to use Nitro to populate a [csm::NitfIsd](https://github.com/sminster/csm/blob/master/NitfIsd.h) for CSM.  

I am having trouble figuring out how to do this without rereading the file or redoing all the write logic to generate all the parts as strings.

I need:
- NITF Header as a string
- Each File TRE as a string
- Each Image Header as a string
- Each Image TRE as a string
- Each DES as a string

At a minimum it would be useful if TREs, DESegments, and ImageSegments also stored the file offset and length(TRE) so that the raw header can be directly read.  Alternately I think if the nitf_Writer_write*() methods were public I could write the components to in memory buffers.

Does anyone have any recommendations?

**Comment by JonathanMeans** [comment]
So if I'm understanding this correctly, you've already read the NITF into NITRO, and you want to convert it to `csm::NitfIsd` without having to re-read the file?

`NITF_API` and `NITF_PROT` expand to the same thing, so if you're using the C layer, I believe you can just use those like you want. 

The other approach, `FileHeader::getImageInfo()`, for example, returns a `nitf::ComponentInfo` which has the length of the subheader and data for that particular image. It's not terribly nice, but you can sum the appropriate lengths to get whatever offset you need.

Although if you're trying to grab the string by the file offset anyway, maybe it's better to just use the appropriate `cms::NitfIsd` constructor.

**Comment by alanlav** [comment]
Yes you are correct I already have the image loaded with Nitro.

I need to directly populate the `csm::NitfIsd` because the file is not accessible in file system.

I am experimenting with direct calls to the `nitf_Writer_writeHeader()` and a memory buffer for the IOInterface.
