### ISSUE TITLE
ModuleNotFoundError: No module named 'nitf'

### ISSUE THREAD

**Issue by sudhakara-rao** [mdaus/nitro#202]
my Python environment (Windows 7 & ver 3.7.4), Anaconda

I installed the nitro package ($conda install -c conda-forge nitro). Got installed, now I want to use module import problem

Now my problem is while importing nitf functions on python interpreter -

>>> from nitf import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nitf'
>>>

Path seems to be ok.

**Comment by bradh** [comment]
Possibly a problem in conda. Have you tried reporting there?
