### ISSUE TITLE
Bug in ImageIO myResidual calculation can cause seg fault

### ISSUE THREAD

**Issue by BryanZeigler** [mdaus/nitro#203]
The bug is in lines 4960-4965 of modules/c/nitf/source/ImageIO.c.  myResidual is an unsigned integer, so it cannot be negative.  The "if (myResidual < 0)" case can never happen.  Instead of myResidual being set to 0 in such a case, it is a very large positive number, which can result it a seg fault.

**Comment by BryanZeigler** [comment]
I submitted a pull request for this issue: https://github.com/mdaus/nitro/pull/204.  I'm not sure whether I need an issue, too.  If not, please close this.

**Comment by JDanielSmith** [comment]
Merged pull-request #204
