### ISSUE TITLE
test_writer_3++ cannot read/write compressed images

### ISSUE THREAD

**Issue by ctophermorgan** [mdaus/nitro#252]
I am using test_write_3++ as the template for reading and writing NITFs which stores the image bands and DES data as temporary files during the read and then uses those files during the write to pass through the image and des segements.

As long as the NITFs are not compressed this works fine. However, for compressed images, the output NITF is roughly twice as large and the performance is extremely slow.

My application passes image segments through to the output NITF while making modifications to the NITF header and des segments (XML DATA). 

Is there a better approach that handles both compressed and uncompressed NITF files?

Examples (both test_writer_3++ and my application exhibit the same behavior):
Input1 (compressed): 4.9 MB, rows=cols=10208, nbands=1, bits/pixel=8, bits/row=bits/col=10, bits/pixel/horizontal=bits/pixel/vertical=1024, IC=C8
- output file is 9.2MB and takes 30 minutes

Input2 (un-compressed): 268 MB, rows=cols=15410, nbands=1, bits/pixel=8, bits/row=bits/col=16, bits/pixel/horizontal=bits/pixel/vertical=1024, IC=NC
- output file is 268MB and takes approx 15 seconds

**Comment by JDanielSmith** [comment]
It looks like `nitf::Reader` and `nitf::Writer` might suit your needs; here’s some sample code that changes a value in the `FileHeader` (lightly modified from the **strip_invisible_segments.cpp** test)
```
static void changeFileHeader(const std::string& inputPathname, const std::string& outputPathname)
{
    if (nitf::Reader::getNITFVersion(inputPathname) == NITF_VER_UNKNOWN)
    {
        throw std::invalid_argument("Invalid NITF: " + inputPathname);
    }

    nitf::Reader reader;
    nitf::IOHandle io(inputPathname);
    nitf::Record record = reader.read(io);

    nitf::FileHeader fileHeader = record.getHeader();
    auto fileTitle = fileHeader.getFileTitle();

    auto strFileTitle = fileTitle.toString();
    str::replaceAll(strFileTitle, " ", "*"); // fixed length

    fileTitle.set(strFileTitle);
    record.setHeader(fileHeader);

    nitf::Writer writer;
    nitf::IOHandle output(outputPathname, NITF_ACCESS_WRITEONLY, NITF_CREATE);
    writer.prepare(output, record);
    writer.setWriteHandlers(io, record);
    writer.write();
}
```

**Comment by JDanielSmith** [comment]
It looks like `nitf::Reader` and `nitf::Writer` might suit your needs; here’s some sample code that changes a value in the `FileHeader (lightly modified from the **strip_invisible_segments.cpp** test)
```
static void changeFileHeader(const std::string& inputPathname, const std::string& outputPathname)
{
    if (nitf::Reader::getNITFVersion(inputPathname) == NITF_VER_UNKNOWN)
    {
        throw std::invalid_argument("Invalid NITF: " + inputPathname);
    }

    nitf::Reader reader;
    nitf::IOHandle io(inputPathname);
    nitf::Record record = reader.read(io);

    nitf::FileHeader fileHeader = record.getHeader();
    auto fileTitle = fileHeader.getFileTitle();

    auto strFileTitle = fileTitle.toString();
    str::replaceAll(strFileTitle, " ", "*"); // fixed length

    fileTitle.set(strFileTitle);
    record.setHeader(fileHeader);

    nitf::Writer writer;
    nitf::IOHandle output(outputPathname, NITF_ACCESS_WRITEONLY, NITF_CREATE);
    writer.prepare(output, record);
    writer.setWriteHandlers(io, record);
    writer.write();
}
```
