### ISSUE TITLE
2.10.1 upgrade from 2.9 causing program abort and segmentation faults when working with TREs (creation and cloning)

### ISSUE THREAD

**Issue by ctophermorgan** [mdaus/nitro#329]
I recently upgraded to 2.10.1 from 2.9. My application is now crashing when attempting to create a TRE. The code was working with previous versions, 2.7 and 2.9. I cannot share the TRE but it is similar to ACCHZB in that it has nested loops. I was hoping you may be able to recreate the problem by creating a ACCHZB TRE. 

NUM_OF_ITEMS1
LOOP 1
   ITEM1_ID
   NUM_OF_ITEMS2
   LOOP 2
      ...

The TRE is created. I can setField NUM_OF_ITEMS1 but the abort occurs when I setField ITEM1_ID.

**Comment by bradh** [comment]
Can you provide a minimal compilable example that reproduces the problem (with ACCHZB or some other TRE)?

**Comment by ctophermorgan** [comment]
No, unfortunately. I do not have an open development environment where that is possible. 

I instantiate the TRE and use setField like https://github.com/mdaus/nitro/blob/master/modules/c%2B%2B/nitf/tests/test_tre_create.cpp. The difference being that I must create the optional fields within loops and it does not appear to work the way it did in 2.9. 

Would you be able to create an example for a slightly more complicated TRE like ACCHZB that has loops and verify if it works?

I did use WAF to build the NITRO source as I have in the past.

**Comment by ctophermorgan** [comment]
Could there be something in my build that is now dated? Is there anything new when building with 2.10?

statically linked libraries: -lnitf-c++ -lexcept-c++ -lsys-c++ -lstr-c++ -lmt-c++ -lnitf-c -lcgm-c -lnrt-c
dynamically linked libraries: -lm -lrt -pthread


---- Example for the issue with creating a TRE 

<include import/nitf.pp>

nitf::TRE tre("HISTOA", "HISTOA");   // allocates fields SYSTEM .. NEVENTS
tre.setField("SYSTYPE", "M1");
tre.setField("PDATE[0]", "20200210184728");   // aborts program; worked prior to 2.10


---- Example for the issue with cloning a raw TRE into a TRE object

<include import/nitf.pp>

nitf_TRE* rawTre;
nitf_Error error;

std::string rd = "begin1020030004ABCDEFend"

rawTre = nitf_TRE_construct("TESTxyz", NITF_TRE_RAW, &error);
nitf_TRE-setField(rawTre, "raw_data", (char*)rd.c_str(), rd.size(), &error);

nitf::TRE cloneTre(rawTre);   // leads to free(): invalid size(): in libc.so.6 when the program exits; worked prior to 2.10

**Comment by JDanielSmith** [comment]
This code also fails in 2.9:
```
<include import/nitf.pp>

nitf::TRE tre("HISTOA", "HISTOA"); // allocates fields SYSTEM .. NEVENTS
tre.setField("SYSTYPE", "M1");
tre.setField("PDATE[0]", "20200210184728"); // aborts program; worked prior to 2.10
```
Second is now fixed.
