### ISSUE TITLE
Modifying an NITF header in-place?

### ISSUE THREAD

**Issue by swarn** [mdaus/nitro#33]
I'm looking to add a TRE to an NITF header (or replace it, if it already exists). I see examples of strictly reading or writing, and I could read, modify the Record, then write a copy. But is it possible to modify the header without copying the whole file?

This and the last issue I posted seem possibly better suited to a mailing list than an issue tracker, but nitro-nitf-users over at sourceforge looks abandoned. Let me know if I should ask my questions elsewhere.

**Comment by asylvest** [comment]
This is the best spot to ask questions so no worries there...

To make sure I understand what you're asking... you've got a NITF that's already written to disk that (possibly) contains a TRE of interest along with whatever other stuff in the file (image segments, etc.) and you want to add / update just this TRE.  You want to keep all the other contents of the file?

If this is your scenario, you will have to write a new copy of the file.  There's no way (in POSIX in general... not just in NITRO) to open an existing file, seek to a spot and modify just those bytes.  If you use NITRO to read in all of the headers, etc. though, it should be straightforward to round-trip those contents back out.

If the concern is that this file is really large and so the I/O is going to be expensive, it would of course be better to attach this TRE right from the beginning so you didn't have to write twice.  If there's a 3rd party writing the file and you want to attach this TRE to their pre-written file, I think you're stuck.

If I'm misunderstanding what you're asking though, let me know.

**Comment by swarn** [comment]
No misunderstanding at all, and you correctly guessed my reason for asking. I'm getting a large NITF image along with some data, doing some calculations (generating RPC information), then adding that info to the image. I'll copy the image for now, and talk with people about changing our workflow.

Thanks, again!
