### ISSUE TITLE
Windows Build issues 

### ISSUE THREAD

**Issue by linker2424** [mdaus/nitro#355]
So I just built the latest master and ran the installer. From some reason I don't get a bin dir on Windows 10 using CMAKE (no errors were reported and I ran the regression tests successfully ). 

Also, when I download the 2.7 build from here:
https://sourceforge.net/projects/nitro-nitf/files/nitro-nitf/NITRO-2.7/
there's a bin dir with 4 exe(s).

Moreover, when I go to link against my build of the latest version of NITRO I get the following error: 
error C1083:  Cannot open include file: 'std/bit': No such file or directory

 and when I go to:
\program files(x86)\nitro\includes\std\ , the std dir is empty (again this in the post installer directory).

Can anyone successfully build the latest NITRO on Windows and get a bin dir after running the installer? Can anyone link against the latest in a Windows 10 Visual studio project ? 

Is there a 2.10 build available anywhere to compare to mine ( sorry I can't find one - I can only find 2.7)?

Lastly, I see this issue here:https://github.com/mdaus/nitro/issues/243
Could this issue be related to my build not having  bin dir after the installer runs?

Thanks all,

**Comment by JDanielSmith** [comment]
Correct download location is https://github.com/mdaus/nitro/releases/tag/NITRO-2.10.3

**Comment by linker2424** [comment]
Dan, thank you for your response. That is the source code I was trying to build from. I still get the same issues that are described above.
