### ISSUE TITLE
Reading specific TRE.

### ISSUE THREAD

**Issue by linker2424** [mdaus/nitro#357]
Ok, I'm struggling with Nitro. Can Nitro read a GLAS\GFM TRE? If so, can someone point me to sudo code? 
Thanks,
EJ

**Comment by bradh** [comment]
GLAS/GFM isn't a single TRE. I don't think that NITRO supports this kind of positioning directly yet. 

Perhaps this would be better as a discussion topic?

**Comment by linker2424** [comment]
Sure, while I have you on the line can you point me to any example code to access any TRE?

**Comment by bradh** [comment]
https://github.com/mdaus/nitro/blob/master/modules/python/nitf/samples/nitf_print.py shows display of a TRE. I don't think that is a valid issue either.
