### ISSUE TITLE
Building NITRO for C

### ISSUE THREAD

**Issue by dashwen** [mdaus/nitro#39]
Hello all,

I apologize if my post does not adhere to the guidelines of reporting an issue...

I would like to integrate NITRO API. The following I wish to achieve is...
         -unpacking nitf file (extract image) and write to file
         -create nitf file with image (jpeg and jpeg2000)

To learn the API, I am using the sample code from NITRO wiki (read nitf file) [http://nitro-nitf.sourceforge.net/wikka.php?wakka=ReadRecord15C](url) -- and resolving header path issues after consecutive attempts of compiling.

The problem I am experiencing are a few linker errors,

`nitf_reader.c:(.text+0x83): undefined reference to `nitf_Reader_getNITFVersion'
nitf_reader.c:(.text+0xd7): undefined reference to `nrt_IOHandle_create'
nitf_reader.c:(.text+0xf9): undefined reference to `nitf_Reader_construct'
nitf_reader.c:(.text+0x12a): undefined reference to `nitf_Reader_read'
nitf_reader.c:(.text+0x14a): undefined reference to `nrt_IOHandle_close'
nitf_reader.c:(.text+0x159): undefined reference to `nitf_Record_destruct'
nitf_reader.c:(.text+0x168): undefined reference to `nitf_Reader_destruct'
nitf_reader.c:(.text+0x194): undefined reference to `nrt_Error_print'
nitf_reader.c:(.text+0x1aa): undefined reference to `nrt_IOHandle_close'
nitf_reader.c:(.text+0x1c5): undefined reference to `nitf_Record_destruct'
nitf_reader.c:(.text+0x1e0): undefined reference to `nitf_Reader_destruct'`

Any suggestions would be greatly appreciated. Thanks!

**Comment by JonathanMeans** [comment]
The easiest way would be to put your `nitf_reader.c` file in `modules/c/nitf/tests`. Then when you run `waf install` the build system will handle everything you need and put the result in `[install_dir]/tests/nitf`.

If you need to build it independently, make sure you're giving the compiler the library files. For g++, assuming `install` is where you've installed NITRO:
 `g++ nitf_reader.c -Iinstall/include install/lib/*.a -ldl`

**Comment by asylvest** [comment]
To back up one step (because I think the wiki you're looking at is actually really old), building the code should be as simple as:

```
python waf configure --prefix=install
python waf install
```

Then like @JonathanMeans said, the quickest way to hack in your own test program would be to put it in a tests folder and it'll automatically get picked up.  For a more permanent solution once/if you get to that point, we can talk some more options.  There are ways to have waf generate all its compiler/linker flags so you can integrate this into your build system.

**Comment by dashwen** [comment]
Thank you for the prompt responses @JonathanMeans @asylvest 

Is there a way to resolve header issues (no such file or directory) with waf? (Waf file modification similar to gnu makefile)

The reason I ask is because it looks as though I am (file not found errors for header). 
Also checked with ./waf --help 

Thanks again.

**Comment by JonathanMeans** [comment]
Can you please show how you are using waf and the error message you are seeing?

If your problems are with includes in your test file, make sure you write the include as if your working directory is `install/include`

e.g. instead of `#include "Reader.h>", you need `#include "nitf/Reader.h"`

**Comment by dashwen** [comment]
That might be the problem, 

below is the error via terminal...
`[ 245/1135] c: c/nitf/tests/nitf_reader.c -> ../target/modules/c/nitf/tests/nitf_reader.c.4.o
../modules/c/nitf/tests/nitf_reader.c:2:18: fatal error: nitf.h: No such file or directory
compilation terminated.
Waf: Leaving directory `/home/ddan/Desktop/nitro/target'
Build failed
 -> task in 'nitf_reader' failed (exit status 1): 
        {task 140630109371280: c nitf_reader.c -> nitf_reader.c.4.o}
['/usr/bin/gcc', '-fPIC', '-Wall', '-Wno-deprecated-declarations', '-O3', '-m64', '-I/home/ddan/Desktop/nitro/target/modules/c/nitf/tests/include', '-I/home/ddan/Desktop/nitro/modules/c/nitf/tests/include', '-I/home/ddan/Desktop/nitro/externals/coda-oss/modules/c++/include', '-I/home/ddan/Desktop/nitro/target/modules/c/nrt/include', '-I/home/ddan/Desktop/nitro/modules/c/nrt/include', '-I/home/ddan/Desktop/nitro/target/modules/c/nitf/include', '-I/home/ddan/Desktop/nitro/modules/c/nitf/include', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE_SOURCE', '-DSWIG_PYTHON_SILENT_MEMLEAK', '-D_LARGEFILE_SOURCE=1', '-DSWIG_PYTHON_SILENT_MEMLEAK=1', '-DNITF_MODULE_EXPORTS', '../modules/c/nitf/tests/nitf_reader.c', '-c', '-o', 'modules/c/nitf/tests/nitf_reader.c.4.o']`

this may be the source of the problem
`//nitf_reader.c
#include <nitf.h>
`

I will try the above suggestions

**Comment by dashwen** [comment]
The above suggestions helped. I have the appropriate binary (nitf_reader) in my [install dir]/tests/ folder.

The sample code used from the wiki is not working as I expected. I receive no errors upon running the binary although passing an argument (sample.ntf) produces no result. 

Thanks again for your help

**Comment by JonathanMeans** [comment]
That program is just a demonstration of how you could get nitf_Readers and nitf_Records from a file. It is expected that it doesn't do anything. Take a look at modules/c/nitf/tests and modules/c++/nitf/tests for more practical example code.

**Comment by dashwen** [comment]
For unpacking an image from a nitf file, would "test_image_loading.c" be the practical example code used in taking care of my objective?

Looking into the code, it does take a buffer of memory that is read from a nitf. Any clarifications would be greatly appreciated.

**Comment by asylvest** [comment]
Yep (or `test_image_loading++.cpp` if you prefer C++.  After the `deserializer.read()` call (like 129 of the C++ version), you will have the NITF image data in memory.

**Comment by dashwen** [comment]
Perfect, thanks for the clarification. I prefer C since I will be implementing on an embedded device.

Upon running the binary, it looks as though it is having trouble reading the image as an instance of an object (pardon if I said it incorrectly)

error listed below
`ddan@ddan-VirtualBox:~/Desktop/nitro/tests/nitf$ ./test_image_loading 2011_308_10_03_18_333_00023.014
Error [Invalid decompression] (../modules/c/nitf/source/PluginRegistry.c, 711, nitf_PluginRegistry_retrieveDecompConstructor): 'Decompression handlers not set' : Couldnt spawn deserializer
`

Assume the nitf file _contains_ a jpeg image. I looked through PluginRegistry.c to see if there were any leads to setting a decompression handler but having trouble locating it. I assume libjpeg of some form needs to be called (used for decompression).

Thanks again for your responses guys, it has been a great deal of help.

**Comment by asylvest** [comment]
Yes, the way NITRO handles both TREs and compression/decompression is via plugins.  If you did a full `waf install`, there should be an `<install dir>/share/nitf/plugins` directory which should include a `LibjpegDecompress.so` (if `libjpeg` isn't found on your machine, it won't build it, so make sure it's there).  Then the easiest way to point NITRO to this is to set your `NITF_PLUGIN_PATH` environment variable to that directory.  When you do that, `test_image_loading` should automagically find the plugin and decompress it for you.

**Comment by dashwen** [comment]
I do see a dynamic library of `libjpegDecompress.so`. I did a `./waf dumpenv` to see which environment variables were enabled prior to `./waf install`, the dump is shown below:

`-DSWIG_PYTHON_SILENT_MEMLEAK -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
`

I did a quick search on the NITRO wiki to learn more about plugins and nitro but there was not much information.

Also, is there anyway to build and use libjpeg as a static library (.a) and use as a plugin?

**Comment by asylvest** [comment]
`waf dumpenv` actually tells you the compiler defines that are set.  When I say environment variable I literally mean `setenv NITF_PLUGIN_PATH `pwd`/install/share/nitf/plugins`.

There is a way to statically link in the TRE plugins (at configure time you use the `--enable-static-tres` flag and you then have to do a couple things in your application itself to explicitly load it at runtime - see `test_static_plugin.cpp` for an example), but we don't currently have the build system set up to allow you to do this with the JPEG plugin.  If you don't like setting the environment variable, you can do this in your application instead by calling `nitf_PluginRegistry_loadDir()` and pointing it to the directory the plugins are in (`install/share/nitf/plugins` again).

**Comment by dashwen** [comment]
I was able to successfully point NITRO to the plugins directory and after running `test_image_loading.c`, it is able to decompress the image. 

input 
`2011_308_10_03_18_333_00023.014` (an nitf file containing 1 jpeg image)

output
`File: 2011_308_10_03_18_333_00023_014_0__528_348_8_band_0.out
File: 2011_308_10_03_18_333_00023_014_0__528_348_8_band_1.out
File: 2011_308_10_03_18_333_00023_014_0__528_348_8_band_2.out`

I am unfamiliar with the term `band` and how it relates to image output. My goal is to achieve one jpeg file in which I can open in my viewer. Is there a way to encapsulate the multiple bands into one file?

**Comment by asylvest** [comment]
OK excellent - glad this worked.

We're using "band" to mean the channel/color in the image (i.e. red band, green band, blue band).  You make one call to `nitf_ImageReader_read()`, telling it all the bands you want to read (by filling out `bandList`).  NITRO will put these bands in contiguous memory regardless of how they were in the NITF/JPEG (there are a number of ways bands can be interleaved in a NITF).

So, you could take those three buffers and use `libjpeg` or whatever you want to write them out yourself...

**Comment by dashwen** [comment]
Ah, so my understanding is that I have two options...

- Make a call to `nitf_ImageReader_read()` providing it all the bands I want to read.
or
- Use libjpeg to write the file out myself providing the bands as input -- **preferred**

It looks like I may have to investigate libjpeg source code to achieve my solution. I will try what you suggested and report my findings...

**Comment by dashwen** [comment]
@asylvest Can you elaborate on using `libjpeg` to write the three buffers out?

**Comment by asylvest** [comment]
So from NITRO's point of view, its "job" is to know how to read NITF files.  When you call `nitf_ImageReader_read()`, it'll read those bands into memory for you.  In the case of a C3-compressed NITF (i.e. one with JPEG compression), it'll decompress it for you and give you the uncompressed imagery in memory.  At that point, your application has the image in memory and can do whatever you want with it.  In your case, it sounds like you'd want to make a call to `libjpeg` to recompress the imagery and write out a JPEG file.  To do that, you'd need to read the `libjpeg` documentation. :o)

**Comment by PaulBellefleur** [comment]
Is it possible do the above process backwards? As in take the output files from test_image_loading++.cpp and place them back into a nitf File. I know that you can copy Image data using nitro but I'm Interested in specifically extracting the raw band data... lets say for c3 and c8 compressed nitf images and then writing that band data to a new nitf File. Perhaps there is a test program that does something similar to this?
