### ISSUE TITLE
NITRO Compilation under Windos 7 and Visual Studio 2010

### ISSUE THREAD

**Issue by agustinvaquero** [mdaus/nitro#40]
Firstly... My intention is construct a Visual Studio 2010 project 
  for reading incrusted jpeg in a nitf file...
  for writing jpeg file into nitf file..

Here are the Steps... I do...

 Install Python 2.7
 Install Visual Studio 2010
 Install nitro-nitf-2.7-win64-r1157-setup.exe // From Sourceforge...
/* Download nitro-nitf-2.7-r1157-src No !!*/
 Download Nitro Master form Github
 
 Execute cmd with "Visual Studio x64 Win64 Command Prompt (2010)" >>
         python .\waf configure

 at the path: nitf-master\nitro\

 obtaining:

 ******************************
 ******************************

 Checking for platform                    : win32
Checking for program CL : ok c:\Program Files (x86)\Microsoft V
isual Studio 10.0\VC\BIN\x86_ia64\CL.exe
Checking for program CL : ok c:\Program Files (x86)\Microsoft V
isual Studio 10.0\VC\BIN\x86_amd64\CL.exe
Checking for program CL : ok c:\Program Files (x86)\Microsoft V
isual Studio 10.0\VC\BIN\CL.exe
Checking for program CL : ok c:\Program Files (x86)\Microsoft V
isual Studio 10.0\VC\BIN\amd64\CL.exe
Checking for program CL : ok c:\Program Files (x86)\Microsoft V
isual Studio 10.0\VC\BIN\amd64\CL.exe
Checking for program LINK : ok c:\Program Files (x86)\Microsoft V
isual Studio 10.0\VC\BIN\amd64\LINK.exe
Checking for program LIB : ok c:\Program Files (x86)\Microsoft V
isual Studio 10.0\VC\BIN\amd64\LIB.exe
Checking for program MT : ok c:\Program Files (x86)\Microsoft S
DKs\Windows\v7.0A\bin\x64\MT.exe
Checking for program RC : ok c:\Program Files (x86)\Microsoft S
DKs\Windows\v7.0A\bin\x64\RC.exe
Checking for msvc : ok
Checking for msvc : ok
Checking for header inttypes.h : not found
Checking for header unistd.h : not found
Checking for header getopt.h : not found
Checking for header malloc.h : ok
Checking for header sys/time.h : not found
Checking for header dlfcn.h : not found
Checking for header fcntl.h : ok
Checking for header check.h : not found
Checking for header memory.h : ok
Checking for header string.h : ok
Checking for header strings.h : not found
Checking for header stdbool.h : not found
Checking for header stdlib.h : ok
Checking for header stddef.h : ok
Checking for function mmap : not found
Checking for function memmove : ok
Checking for function strerror : ok
Checking for function bcopy : not found
Checking for type size_t : ok
Checking for const keyword : ok
Checking for unsigned short : ok
Checking for unsigned char : ok
Checking for library m : not found
Checking for library rt : not found
Checking for library sqrt : not found
Checking for function gettimeofday : not found
Checking for function clock_gettime : not found
Checking for function BSDgettimeofday : not found
Checking for function gethrtime : not found
Checking for function getpagesize : not found
Checking for function getopt : not found
Checking for function getopt_long : not found
Checking for function isnan : not found
Checking for type hrtime_t : not found
Checking system type sizes : ok
Checking for sizeof long long : 8
Checking for sizeof long : 4
Checking for bigendian : False
Checking for sizeof double : 8
Checking for sizeof short : 2
Checking for sizeof int : 4
Checking for sizeof float : 4
Checking for 64-bit system : ok
Checking for program javac : not found
Checking for program java : not found
Checking for program jar : not found
Checking for program python : ok C:\Python27\python.exe
Checking for Python version : 2.7.13
Checking for library python27 : ok
Checking for program python2.7-config : not found
Checking for program python-config-2.7 : not found
Checking for header Python.h : Could not find the python development
headers
Checking for Python lib/headers : the configuration failed (see 'c:\De
sa\nitf-master\nitro\target\config.log')
Checking for program matlab : not found
Checking for Java lib/headers : set JAVA_HOME in the system environme
nt
'configure' finished successfully (14.286s)

**************************************************
after this.. I execute
c:\Desa\nitf-master\nitro>python .\waf build
 obtainig:

 *******************************
 *******************************
Waf: Entering directory c:\Desa\nitf-master\nitro\target' Waf: Leaving directoryc:\Desa\nitf-master\nitro\target'
object 'mem-c++' was not found in uselib_local (required by 'mt-c++')

this ocurs with the source forge 2.7 sources...
with github its ok... >>  I achive compile it whith WAF and produce all the Target files...

******************************
*****************************

I´ve contruct a project with 
   the *.c NITRO FIles... ( DateTime.c .. Utils.c)
   the *.c NITF Files... (BandInfo..writer.c)
 then I add the file test_image_loading.c for trying read the jpeg image...

In one machine I have problem during the LoadLybrary windows api function (it returns null ... when i try to load all the dlls inside the plugins chapter...)

and in another machine with others dlls, it loads ok but i have the following problem...
   I am try to read a NITF file... with the reading example...
obtaining all the header data correctly ... rows=256 columns = 256 jpegcompresion = C3...
But the program crash at READBLOCk IO function... why ?!
Since WAF don´t say which instructions are executing.... If it´s posible to do a compilation without WAF ?

My intention is migrate this library to RTOS vxWorks, but after this, i Want to read and write jpeg image at NITF 2.0 File .

If it´s posible do this in a completely static way... taking the externals plugins as loading objects .o or librarys .a this is... without dll´s ...
Its is posible obtain teh source code of all DLL´s ?! and try to debug it later ?!
Where is the Dll source codes ? (since is installed from the nitro.exe instalation exe file)
Thank you !!

**Comment by asylvest** [comment]
A few things...

I would recommend doing a `python waf install` and then setting your `NITF_PLUGIN_PATH` environment variable to `<install dir>\share\nitf\plugins`.  The `<install dir>` can be set at `waf configure` time (`python waf configure --prefix=/path/to/install`).  This should tell NITRO where to find all the plugins.

It's been awhile since I've personally used the JPEG decompression plugins in NITRO, but so far as I know, it should work (note that we currently only support JPEG decompression/reading - we do not support JPEG compression/writing... we do support JPEG-2000 both reading and writing though).  You mention NITF 2.0... by far the majority of our testing is with NITF 2.1, so it's possible there's something not working properly with 2.0s.  Is it possible for you to post the NITF you're trying to read somewhere that I could access?

NITRO builds its TRE, JPEG, and JPEG 2000 support dynamically (so DLLs on Windows).  It's possible to tell it to build its TREs statically but we haven't updated the build system to support static linking for JPEG and JPEG 2000 (if you do this, please put in a pull request to contribute it back :o) ).  However, I don't think this is what's causing your crash.

The actual source file for the JPEG decompressor (which uses libjpeg internally) is in modules/c/jpeg/source/LibjpegDecompress.c).

**Comment by JDanielSmith** [comment]
We have no (unsupported) Windows 7 machines available; and we're using (much) more recent tool-chains than VS2010.
