### ISSUE TITLE
NITF Exception: Unable to find tag, 'PLATFORM_PITCH', in TRE hash for TRE 'SENSRA'

### ISSUE THREAD

**Issue by joshriccio** [mdaus/nitro#42]
When setting the PLATFORM_PITCH field in the TRE SENSRA using java I get the following exception. 

NITF Exception: Unable to find tag, 'PLATFORM_PITCH', in TRE hash for TRE 'SENSRA'

This document,http://www.gwg.nga.mil/ntb/baseline/docs/stdi0002/stdi_0002.pdf, says that PLATFORM_PITCH should exist. Am I mistaken?

**Comment by asylvest** [comment]
The field is named PLTPITCH in NITRO (we usually have these field names match the GWG doc so not sure offhand why these are all abbreviated... may be based on an earlier version of the document).  The easiest way to see the field names is to look at the underlying C code which lists all the field names:

https://github.com/mdaus/nitro/blob/master/modules/c/nitf/shared/SENSRA.c

**Comment by joshriccio** [comment]
Great thank you!
