### ISSUE TITLE
Clarify/migrate documentation

### ISSUE THREAD

**Issue by s-martin** [mdaus/nitro#54]
I assume that the documentation located at http://nitro-nitf.sourceforge.net/wikka.php?wakka=HomePage is still somehow valid (at least there's much more documentation available than here at Github).

It would be helpful for interested users like me, if this documentation would be migrated to Github as well or if there would be at least a pointer from here to the SF wiki to indicate that this documentation is still valid.

**Comment by JDanielSmith** [comment]
Copying to new **docs** directory.
