### ISSUE TITLE
Clarify license terms

### ISSUE THREAD

**Issue by s-martin** [mdaus/nitro#55]
Please clarify the intended licensing in the Readme.md.

I found here at Github the COPYING (for GPLv3) and COPYING.LESSER (for LGPLv3) files. 
However in the project settings here GPLv3 is indicated.
The old docs at http://nitro-nitf.sourceforge.net/wikka.php?wakka=HomePage indicate it's LGPLv3.

So is it a dual licensing model (under which conditions?) or only GPLv3 or only LGPLv3?

For me it would be crucial, which license applies, because if I would use NITRO in one of our projects, I could not open the source code (which would dynamically link NITRO) for contractual reasons.

**Comment by asylvest** [comment]
Sorry for the confusion - NITRO is licensed only under LGPLv3.  I have updated the repo files such that GitHub correctly picks that up... each source file has a banner also indicating LGPL.

**Comment by s-martin** [comment]
Thanks for the fast response.
