### ISSUE TITLE
Building shared libs fails

### ISSUE THREAD

**Issue by s-martin** [mdaus/nitro#62]
When building with `--shared` linking fails, because libjpeg is built as shared lib, but later still expected as static lib.

```
Build failed
-> missing file: 'C:\\_MYDATA\\Projekte\\nitro\\target\\externals\\coda-oss\\modules\\drivers\\jpeg\\jpeg-9\\libjpeg.lib'
```

Also there are no "lib" files built under Windows, which are required to use DLLs.

Env: Windows 7, VS2010

**Comment by asylvest** [comment]
Yes, we should update `build.py` to not expose the `--shared` option on Windows - it will not work (beyond the issues you mention, we need ifdefs with the right `declspec` everywhere which we do not do.

If this is a priority for you, let us know and we'll add it to the queue...

**Comment by s-martin** [comment]
Considering the LGPL indeed dynamic linking would be a priority for us, otherwise we cant use Nitro.

**Comment by s-martin** [comment]
I addition I would also suggest to have in the end only one nitro DLL.

**Comment by asylvest** [comment]
I'm working to identify someone who has availability to update the build system to support this (I'm assuming your target environment is Windows?  It'll work with minimal effort in Linux...).  The way the build system is set up, there will be a one-to-one mapping between each static library and a DLL instead (so you'll end up with 5-10 DLLs).

**Comment by s-martin** [comment]
Yes, our target is Windows

**Comment by JonathanMeans** [comment]
@s-martin  I've started working the issue. In the mean time, I've discovered a hack which may get you what you need, or enough to get going.

```
rmdir /s install
python waf clean configure --prefix=install install
python waf configure --prefix=install --shared 
```
If you try to do `python waf install` from this point, it fails for me. But I am able to do

```
python waf install --target=nitf-c++
python waf install --target=j2k-c
```

and get most of the dlls.

**Comment by s-martin** [comment]
Thanks I'll try that in the meantime.

**Comment by JDanielSmith** [comment]
See #86 and #144; leaving #144 open as it's the newest.
