### ISSUE TITLE
CMake and other stuff

### ISSUE THREAD

**Issue by hobu** [mdaus/nitro#67]
I wasn't previously aware of this fork, but I had been maintaining one at https://github.com/hobu/nitro for quite a while. My fork mostly just adds CMake support along with a few other small bug fixes. It seems as though you guys are actively updating in support of new efforts, and if you are planning to roll a new release, maybe you are interested in the contributions I've made.

**Comment by asylvest** [comment]
Hey Howard.  This is actually the active, official NITRO development repo now (i.e. we have moved off of SourceForge).  I remember talking with you a few years back about your CMake and other updates.  If it's easy for you to put out a PR, we'll certainly take a look.  Internally we don't have a need for CMake, but if it easily sits side by side and is useful to other folks, we'd strongly consider merging it in.

**Comment by JDanielSmith** [comment]
CMake support has been added.
