### ISSUE TITLE
Alternate python wrappers

### ISSUE THREAD

**Issue by tclarke** [mdaus/nitro#70]
I was trying to use the python wrappers with 3.6 and was having some compatibility issues. Mostly with how strings, bytes, etc. are handled. Since the API isn't the most pythonic interface out there I took a crack at starting a cython based wrapper utilizing buffers, properties, etc. Changed some names to be PEP8 compliant, etc.
It's far from complete at this point since I'm mostly interested in generation right now. Is there any interested in incorporating this into the mainline? Or should I just keep it on my fork?

**Comment by asylvest** [comment]
@tclarke thanks for letting us know.  It's a bit of a double-edged sword... Swig is great at auto-generating bindings for you but as you say, it's klunky at things.  We have had requests from users in the past to have nicer bindings.  I'm not sure how quickly we'd have bandwidth to integrate into master but we'd definitely be interested in taking a look at what you have if it's easy to either put in a PR or point us to the directory on your fork.
