### ISSUE TITLE
Enabling kakadu support for Nitro

### ISSUE THREAD

**Issue by geospatialDev** [mdaus/nitro#71]
I have created a NITF writer using NITRO. I have a kakadu license and want to enable writing j2k compressed files. How do I turn on the kakadu support for NITRO? I know how to do it using GDAL but am trying to do it using Nitro?

I tried waf configure --with-j2k=kdu
I get an error 
JPEG2000 library                                                                                 : not found

**Comment by asylvest** [comment]
When we updated to a more recent version of OpenJPEG a few years ago, we effectively dropped maintaining Jasper (significantly worse performance compared to the latest OpenJPEG) and Kakadu (didn't have a license available to compile it at the time).  Two options...
1. We still don't have a license, but if you're interested in getting it working, I can give you some pointers as to what you'd need to do.  If you're successful, you can put in a pull request and I'll merge it in.
2. As bandwidth allows, we're working on an updated interface which will allow you to do the J2K compression yourself outside of NITRO and hand NITRO just the compressed bytes.  This would allow you to use Kakadu directly without NITRO updates.  Realistically it may be a few months before we get that into the baseline.

Let me know if you'd like some pointers on option 1; otherwise I can let you know when option 2 is integrated.

**Comment by geospatialDev** [comment]
Yes I would like to have pointers to 1.

**Comment by asylvest** [comment]
OK, so under modules/c/n2k...
1. Add an external/kakadu/wscript file.  This needs to...
  - Set HAVE_KAKADU_H
  - Set `conf.env['HAVE_J2K'] = True`
  - Have a check for Kakadu on your path, potentially adding a --with-kakadu-home option.  Look at externals/coda-oss/modules/drivers/jpeg/wscript for something similar, but you don't need to implement the parts that build the library from source.  Your conf.check() will need to set uselib_store=J2K
2. Update modules/c/j2k/wscript.  This needs to basically add a kakadu version everywhere you see OpenJPEG
3. At this point in theory, `waf build --target=j2k-c` should build `KakaduImpl.cpp`.  If anything in the API has changed in NITRO in the past couple years, this may need some finessing.  You'll want to match the API that `OpenJPEGImpl.c` fulfills.

I'm sure I missed some steps and didn't provide enough info.  Feel free to post stumbling blocks as you run into them.

**Comment by geospatialDev** [comment]
Adam,
I was wondering if there are examples of user defined ImageWriters for Nitro.
I need to get data compressed using some external compressor and put it to an Nitf. The only reference I got is for a non-existent link http://nitro-nitf.sourceforge.net/wikka.php?wakka=StealJpeg.

Thanks
Reena

**Comment by asylvest** [comment]
So, two ways you can go here in the immediate term.  There's an example of doing both of these in SIX (SIX is a library that writes particular kinds of NITFs, using NITRO for the low-level stuff):
1. The conventional NITRO way is to provide a custom write handler.  See https://github.com/ngageoint/six-library/blob/master/six/modules/c%2B%2B/six/include/six/Adapters.h for some examples and https://github.com/ngageoint/six-library/blob/master/six/modules/c%2B%2B/six/source/NITFWriteControl.cpp for them being used
2. More recently, we've started using NITRO's knowledge of the file structure and headers but doing the lowest-level writing ourselves to most flexibly/efficiently write things out.  See https://github.com/ngageoint/six-library/blob/master/six/modules/c%2B%2B/six.sicd/source/SICDByteProvider.cpp and the associated unit test for an example of how to do this.  SICDByteProvider is assuming you're writing out a normal, uncompressed image, but you could do the same thing with a J2K-compressed image.

This latter approach is what we're planning on implementing for J2K compression in the near future (and a more generalized version of that base ByteProvider class will move to NITRO).  If you come up with something general and are able to put out a pull request, we'll look to see if we can incorporate it.

Let me know if you need more info.

**Comment by asylvest** [comment]
We just merged in functionality to support allowing you to do your own J2K compression outside of NITRO: https://github.com/mdaus/nitro/pull/85.

See https://github.com/mdaus/nitro/blob/master/modules/c%2B%2B/nitf/tests/test_create_nitf_with_byte_provider.cpp, looking at the placeholder spots for where you'd do compression yourself.

**Comment by geospatialDev** [comment]
Thanks Adam. I will try it out.
