### ISSUE TITLE
Using openjpeg with NITRO

### ISSUE THREAD

**Issue by mpolder** [mdaus/nitro#72]
I noticed a pull request to use OpenJPEG 2.3 instead of 2.0 with NITRO. I just started using NITRO myself and am able to open a NITF 2.1 commercial image and user the JasPer decompression code provided. I noticed that modules\c\j2k\source has implementation files for JasPer, Kakadu, and OpenJPEG, while previous versions of NITRO (e.g. 2.5) had directories under modules\c for JasPer and jpeg that had additional source code files (e.g. JasPerDecompress.c) that enabled JasPer (or purportedly OpenJPEG now) to be used for decompression. With the current NITRO should OpenJPEG "work out of the box" or do I need to write code to have it loaded as a plugin.

thanks,
matthew

**Comment by asylvest** [comment]
Yeah we're gradually updating to OpenJPEG 2.3 (doing some integration work in an internal repo first before pushing it out to NITRO), but master is working with OpenJPEG 2.0 and should work out of the box.  If you do a...
```
waf configure --prefix=install
waf install
```

You'll see J2K compression and decompression plugins in `install/share/nitf/plugins`.  If you're having issues, post the commands you're running and logs of your output and I'll take a look.
