### ISSUE TITLE
shared build fails on linux

### ISSUE THREAD

**Issue by outburstx** [mdaus/nitro#86]
A clean checkout of nitro does not build on the following configuration:

OS: 64-bit CentOS 7
gcc: 4.8.5

I ran the following commands:

`> python waf configure --enable-debugging --prefix=installed --shared`
`> python waf build`

And got the following errors:

`/bin/ld: cannot find -lnrt-c.2.7`
`collect2: error: ld returned 1 exit status`
`/bin/ld: cannot find -lnrt-c.2.7`
`collect2: error: ld returned 1 exit status`
`/bin/ld: cannot find -lnrt-c.2.7`
`collect2: error: ld returned 1 exit status`

...

`Build failed`
` -> task in 'test_core_values' failed (exit status 1): 
        {task 24244816: cprogram test_core_values.c.6.o -> test_core_values}
['gcc', '-fPIC', '-Wl,-E', '-m64', '-pthread', 'modules/c/nrt/unittests/test_core_values.c.6.o', '-o', '/home/d/Downloads/nitro-master/target/modules/c/nrt/unittests/test_core_values', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-Lmodules/c/nrt', '-lnrt-c.2.7', '-ldl', '-lrt', '-lm']`
` -> task in 'test_byte_swap' failed (exit status 1): 
        {task 24244496: cprogram test_byte_swap.c.5.o -> test_byte_swap}
['gcc', '-fPIC', '-Wl,-E', '-m64', '-pthread', 'modules/c/nrt/unittests/test_byte_swap.c.5.o', '-o', '/home/d/Downloads/nitro-master/target/modules/c/nrt/unittests/test_byte_swap', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-Lmodules/c/nrt', '-lnrt-c.2.7', '-ldl', '-lrt', '-lm']`
` -> task in 'test_tree' failed (exit status 1): 
        {task 24245648: cprogram test_tree.c.9.o -> test_tree}
['gcc', '-fPIC', '-Wl,-E', '-m64', '-pthread', 'modules/c/nrt/unittests/test_tree.c.9.o', '-o', '/home/d/Downloads/nitro-master/target/modules/c/nrt/unittests/test_tree', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-Lmodules/c/nrt', '-lnrt-c.2.7', '-ldl', '-lrt', '-lm']`
` -> task in 'test_utils' failed (exit status 1): 
        {task 24245904: cprogram test_utils.c.10.o -> test_utils}
['gcc', '-fPIC', '-Wl,-E', '-m64', '-pthread', 'modules/c/nrt/unittests/test_utils.c.10.o', '-o', '/home/d/Downloads/nitro-master/target/modules/c/nrt/unittests/test_utils', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-Lmodules/c/nrt', '-lnrt-c.2.7', '-ldl', '-lrt', '-lm']`

Is Nitro intended to be used on Linux or is it primarily a Windows library?

**Comment by outburstx** [comment]
Thanks for the quick response.

I tried your workaround, and it does complete without error.
However, it results in a 'lib' directory full of .a and .so files, with many of the .so files being broken links.
So there are several problems, some being obvious;

1) A file called `nitf-c++.2.7.so` is built, but `libnitf-c++.so` is a symbolic link to `libnitf-c++.so.2.7.so`, which doesn't exist.  So I need to fix that symbolic link manually.
2) All of the static libraries are installed as well.  For license-compliance reasons, I don't feel comfortable having static libraries around, so I'll need to remove those manually.
3) `ldd` tells me that `nitf-c++.2.7.so` does not have any shared-library dependencies on any of the other nitro shared libraries (like `nitf-c.2.7.so` or `except-c++.1.0.so`), which leads me to fear that they were statically linked, which in turn makes me worried about license-compliance issues.

So, as you say, there are issues with building as a shared library.
It looks like these have been issues for a while.
Is the problem a lack of in-house experience with 'waf'?  
Would there be any interest in a CMake build system instead?  Do you know what the rationale for using waf was in the first place?

**Comment by JonathanMeans** [comment]
@asylvest would be the right person to talk to about that. I cannot speak for him of course, but he tends to be active on GitHub in the evening.

**Comment by asylvest** [comment]
Hey @outburstx - thanks for letting us know about this.  As you must have noted from past discussion items, there are known issues with shared library support for NITRO.  I think we have sufficient `waf` expertise; it really comes down to staff prioritization... we do want to support shared library building exactly for use cases like yours, but it keeps remaining on our nice-to-have-when-we-have-time-someday list.

If you have the bandwidth to provide some updates to the build system to support it (with `waf`), we'll happily review the pull request. :o)  We've talked off and on about `CMake` but at least in the immediate term are sticking with `waf`.

**Comment by aleichtman** [comment]
Hi all, 
Are there any plans to correct this shared library issue?  The above mentioned work around does the job,  but that said, it would be very nice to have a shared library build capability w/o a work around to support the GNU Lesser General Public License v3.0 licensing that NITRO and CODA-OSS employ.

**Comment by JonathanMeans** [comment]
I'm afraid that this is very low priority for us right now.

**Comment by JDanielSmith** [comment]
Closing this issue; will track in newer #144 https://github.com/mdaus/nitro/issues/144
