### ISSUE TITLE
TREs parsing on windows, but not on linux

### ISSUE THREAD

**Issue by uvayankee** [mdaus/nitro#9]
PluginRegistry.canHandleTRE("AIMIDB") returns TRUE on my Windows dev machine, and FALSE on my Linux build machine.  As a result, my java code on Windows can see the fields inside of the TREs, but the same code on Linux cannot.

PluginRegistry.canHandleTRE returns FALSE for all TREs on LInux, so it seems like a general issue with the TRE code on Linux.

**Comment by asylvest** [comment]
Are you sure you're setting the plugin directory on Linux?  You can do this by either setting the NITF_PLUGIN_PATH environment variable or, from the Java API, calling `loadPluginDir()`.  You'll also want to make sure the plugin you're interested in using got built... either by doing a `waf install` to build everything or explicitly targetting the plugin you want like `waf install --target=AIMIDB`.  The plugin directory should be set to `<installation prefix>/share/nitf/plugins` and if you do an `ls` on that directory, you should see `AIMIDB.so`.

TREs are definitely supported on Linux; we use this functionality internally on a daily basis.  To make sure something strange wasn't happening with the `canHandleTRE()` function specifically, I verified that the underlying C function that the JNI is calling (`nitf_PluginRegistry_retrieveTREHandler`) worked on Linux as expected when using either the NITF_PLUGIN_PATH environment variable or the `nitf_pluginRegistry_loadDir()` C call.  In both cases, `nitf_PluginRegistry_retrieveTREHandler` returned non-NULL which would have resulted in the Java layer returning true.

Let me know if this doesn't work for you and we can do some additional troubleshooting.

**Comment by uvayankee** [comment]
Thanks, the env variable was what I was missing - I started on Windows with the installed version, so the plugin directory step was invisible to me.  I ran into this issue when I was trying to get my code onto a continuous integration server on centos.
