### ISSUE TITLE
Image data spills over to the DataExtensionSegment

### ISSUE THREAD

**Issue by geospatialDev** [mdaus/nitro#98]
This is what I am trying to do:
 Write regular TREs
 Write Custom TREs as ENGDRA in the DataExtensionSegment
 Write multiband image data, compressed, into one segment.

In the output Nitf file, the image data has spilt over to the DataExtensionSegment. The overflow happens when I use all the 7 bands of multispectral data. If I write 1 band or 3 bands then it is fine.

**Comment by JonathanMeans** [comment]
I'm having trouble reproducing the error. Would you be able to share the code you're using to set up the write, or the erroneous NITF output?

**Comment by geospatialDev** [comment]
I cannot share the data. The issue is the size of the image data. Its 7 band, 16 bit 5472 X 999 J2K compressed. I'm using a custom writer to write the compressed data.

compressedWrite()
{
	nitf_Error nError;
	// Declare structure to insert method 
	nitf_UserWriteHandler imageWriteHandler = {
		// Static method to do image writing
		writeCompressedImage,
		// Empty buffer of image size so image write routine 
		//  does not have to dynamically allocate. 
		NULL
	};
	// Set new image writing method into writer
	//  this location in writer is also an addition to the NITRO lib
	m_writer->iface = &imageWriteHandler;
	if (!nitf_Writer_write_userImageWrite(m_writer, &nError))
	{
		LOG_ERROR("nitf_Writer_write_userImageWrite failed " << nError.message);
	}


bool writeCompressedImage(NITF_DATA *data, nitf_IOInterface* output, nitf_Error* error, char* scratchBuffer)
{
	ImageWriterImpl *impl = (ImageWriterImpl *)data;
	nitf_BandSource *bandSrc = nitf_ImageSource_getBand(impl->imageSource, 0, error);
	
	if (!bandSrc)
		LOG_ERROR("nitf_ImageSource_getBand failed");
	
	MemorySourceImpl *memSource = ((MemorySourceImpl*)bandSrc->data);
	if (!memSource || (memSource->data == 0) || (memSource->size == 0))
		LOG_ERROR("Invalid data");

	
	nitf_Off offset = nitf_IOInterface_tell(output, error);
	if (!NITF_IO_SUCCESS(offset))
		LOG_ERROR("nitf_IOInterface_tell Failed ");

	
	if (!nitf_ImageIO_setFileOffset(impl->imageBlocker, offset, error))
		LOG_ERROR("nitf_ImageIO_setFileOffset Failed");


	size_t bytesActuallyWritten = 0;
	
	IOHandleControl *control = (IOHandleControl *)output->data;
	do
	{
		ssize_t bytesThisWrite = -1;

		bytesThisWrite =
				write(control->handle, memSource->data + bytesActuallyWritten, memSource->size);
		if (bytesThisWrite == -1)
		{
			LOG_ERROR("Data write() failed with error " << strerror(errno));
		}
		bytesActuallyWritten += bytesThisWrite;
	} 
	while (bytesActuallyWritten < memSource->size);

**Comment by JonathanMeans** [comment]
Can you show what you get from running `<install_dir>/bin/show_nitf++` on your NITF?

**Comment by geospatialDev** [comment]
[out1.txt](https://github.com/mdaus/nitro/files/2337220/out1.txt)

**Comment by geospatialDev** [comment]
[out1.txt](https://github.com/mdaus/nitro/files/2337232/out1.txt)

**Comment by geospatialDev** [comment]
I'm compressing a huge amount of image data and writing it out with custom code in Nitro. The data is j2k compressed but I don't think that matters. When I write some custom TREs in the DES explicitly since they are huge, the image data seems to overwrite the TREs . The image data is fine when viewed in some software like ENVI but the TREs that I wrote in the DES is garbled.

**Comment by JonathanMeans** [comment]
Are you certain you have the latest version? I noticed a formatting bug in your out.txt that was fixed about a year ago.

I don't believe there would be any problem with explicitly writing it. You are using `nitf_Record_newDataExtensionSegment()`?

**Comment by geospatialDev** [comment]
Yes I'm using nitf_Record_newDataExtensionSegment to create it.
I'm using the released version 2.7 of Nitro.

**Comment by geospatialDev** [comment]
No the data is about 1GB
