### ISSUE TITLE
Uninstalling Nitro 

### ISSUE THREAD

**Issue by PaulBellefleur** [mdaus/nitro#99]
How does one uninstall nitro? Im working on making a nitro rpm for redhat now and I want to test it... but I have nitro currently installed. Ive tried to do python waf uninstall but that command needs certain arguments and Im not exactly sure what they should be.

**Comment by JonathanMeans** [comment]
It looks like some of our subclassing broke waf's built-in `uninstall` command, and no one noticed until you just tried to use it. I'm afraid this is something you'll have to do manually.

(I suppose the best approach would be to do a clean install, get a list of all the files, then write a script to remove the corresponding entries from where you have it installed...)
